### ISSUE TITLE
🔧 [Refactor]

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4116]
## :zap: Refactor ticket

The maintenance page looks not as good as in earlier days sadly. Because base-card melts together with the as well white background, I guess.

<img width="1102" alt="Bildschirmfoto 2021-01-06 um 15 03 28" src="https://user-images.githubusercontent.com/25344101/103779001-69972780-5033-11eb-908b-168674852ece.png">

### Motive

To have a nicer design of the maintenance page.

### Related issues

None

### Implementation

In my opinion there’s a shadow missing around the base-card or the background is not greyish enough like on a similar page:

<img width="660" alt="Bildschirmfoto 2020-12-23 um 08 51 47" src="https://user-images.githubusercontent.com/25344101/102973181-9bb96d00-44fc-11eb-97cb-255041dec8f2.png">

In general we may should use the HTML tags design of `webapp/pages/password-reset.vue`.

### Additional context

To get the maintenance mode running see [webapp/maintenance/README.md](https://github.com/Ocelot-Social-Community/Ocelot-Social/tree/master/webapp/maintenance/README.md).

**Comment by tippanamadhusudan** [comment]
I would like to do this. Please assign it to me.

**Comment by ulfgebhardt** [comment]
I assigned you @tippanamadhusudan 

If you take this issue you may also look into refactoring the whole maintenance thing if you feel confident about that. Its way broader then the current issue states and please don't feel obligated to do more then the original issue intends.

Still the following things need to be done to the maintenance page:

1. Separation from webapp

Currently the maintenance page is deeply entangled into the webapp. This should be seperated. In its own dockerfile completely independed from webapp. The required files for the maintenance page should be store in /maintenance not /webapp/maintenance
![deploy-structure](https://user-images.githubusercontent.com/1238238/107715511-ba9fd880-6ccf-11eb-883f-295309ca962b.png)

2. The page is too complicated

There is too much things going for just a fancy maintenance page. I do not understand why we need our own nuxt running when this could be done by just a simple html file. The only function which is more then displaying a text is the language switcher.
What is your opinion on this? You think its needed? Can we reduce the whole thing to a html somehow served?

As said its not needed to solve any of this, but might be wise to have in the back of your head while doing it. Maybe you can give us some insight what other functionality is there on the maintenance page? What about the language select? Can we use nuxt to generate static pages - like html?

**Comment by tippanamadhusudan** [comment]
Hi, after making changes to maintenance page, I will try to separate maintenance from webapp.

**Comment by ulfgebhardt** [comment]
I gave it a quick try a few days back and it was not as easy as expected - just be aware.

**Comment by ulfgebhardt** [comment]
`I selected a issue for maintenance design. 
For me to get maintenance page, I need to run docker-compose up,
but I am facing the same problem as before where the code I changed is not getting updated. Last time you said that this problem is resolved, so can I know how to resolve the issue I am getting.`


@tippanamadhusudan  The maintenance docker file was not adjusted so that it is linked to the local environment. The maintenance docker file is still a mess. I would like to ask you to implement the binding to the local system by doing the bind yourself. Please commit the dockerfile in your PR aswell.

```
  ########################################################
  # WEBAPP ###############################################
  ########################################################
  webapp:
    image: ocelotsocialnetwork/webapp:development
    build:
      target: development
    environment:
      - NODE_ENV="development"
      # - DEBUG=true
      - NUXT_BUILD=/tmp/nuxt # avoid file permission issues when `rm -rf .nuxt/`
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      - webapp_node_modules:/app/node_modules
      # bind the local folder to the docker to allow live reload
      - ./webapp:/app
```

Here you see the volumes - those are responsible for the local bind. They have to be added in the docker-compose.override.yml
This whole issue is closely tied with the structural problems described in the issue
