### ISSUE TITLE
🚀 [Feature] Base Card Padding To Big On Mobil

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4812]
## :rocket: Feature Request

Base card padding on internal pages is to big on mobil.

`webapp/locales/html/`

#### Problem looks like:

![photo_2021-10-13 12 52 34](https://user-images.githubusercontent.com/25344101/144065119-9789ef39-0bfd-4624-b4ce-ed9e047f88ef.jpeg)

#### Solution:

Is solved for the sender.fm network in PR https://github.com/sender-fm/Sender-Fm-Ocelot-Social-Deploy-Rebranding/pull/14

```css
  @media (max-width: 452px) {
    .ds-container {
      padding: 0;
    }
  }
```

<img width="314" alt="Bildschirmfoto 2021-11-30 um 15 25 00" src="https://user-images.githubusercontent.com/25344101/144067602-fab26bf3-14c9-4de7-a077-9ca92d5645b3.png">
